# Site settings
baseurl = "https://example.org/"
languageCode = "en-us"
title = "Pranoy's Profile"
theme = "hugo-freelancer-theme"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Pranoy Prabhakar"
    description = "My awesome description"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "pranoy.prabhakar@gmail.com"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Pranoy's Portfolio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Pranoy Prabhakar"
        subtitle = "Senior Tester - SDET - Aspiring DevOps Engineer"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Projects"

        [params.portfolio.modal]
            technology = "Technology"
            date = "Tools"
            category = "Language"
            buttontext = "Close"

    [params.skills]
        title = "Skills"
        programminglang = "HTML, CSS, Java, Java Script, SQL, Groovy, C++, VBScript"
        tools = "Eclipse, STS, UFT, ALM, SOAPUI, Jenkins, Oracle SQL Developer, Microsoft Visual Studio, CA Test Data Manager, CA Fast Data Masker, Git, SVN, Maven, Nexus, Microsoft CODE, JIRA"
        framework = "Angular JS, Spring, Hibernate, Angular JS, Selenium WebDriver, Data Driven Framework, Hybrid Framework"

    [params.education]
        title = "Education"


    [params.about]
        title = "About"
        # The about text is splitted into a left and right column
        left = "An enthusiastic <strong>Senior Test Automation Engineer</strong> with more than 6 years of experience in various roles, across a diverse range of industry sectors, also distinguished by my subject knowledge and flexible approach to complex problems like feasibility and approach for automating Enterprise applications. Leads people and organizations departments to achieve outstanding results through digital transformation."
        right = "i am currently staying in Amsterdam, Netherlands but I belong to northern part of india named Madhubani,Bihar. I like travelling, go for a good run and watch movies in my leisure. "

        [params.about.button]
           text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Current Stay"
            # Postal address (add as many lines as necessary)
            address = ["Van Hueven Goedhartlaan 528,", "Amstelveen, Netherlands"]

        [params.footer.social]
            title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-instagram"
                link = "//instagram.com/pranoyprabhakar/"

            [[params.footer.social.networks]]
                icon = "fa-facebook"
                link=  "//facebook.com/pranoy.prabhakar"

            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "//linkedin.com/in/pranoy-prabhakar-b91819134/"

        [params.footer.callme]
            title = "Reach Me Out"
            text = "+31 685568349 pranoy.prabhakar@gmail.com"
